project:
  type: website

title: "DevOps"
author: "Boris Ivan Huarachi Perez" 
theme: [journals] 

website:
  title: "DevOps"
  navbar:
    left:
      - text: Quarto
        menu:
          - text: Introducci贸n
            href: index.qmd
          - text: About
            href: about.qmd

      - text: Docker
        menu:
          - text: Introducci贸n
            href: docker.qmd
          - text: About
            href: about.qmd

      - text: Jenkins
        menu:
          - text: Introducci贸n
            href: jenkins.qmd
          - text: About
            href: about.qmd
      
      - text: AWS
        menu:
          - text: Introducci贸n
            href: amazon.qmd
          - text: About
            href: about.qmd      
      
      - text: Github
        menu:
          - text: Comandos Basicos
            href: indexgit.qmd
          - text: About
            href: about.qmd       
    
    right:
      - text: Contact
        href: contact.qmd

nav:
  - Home: index.qmd
  - About: about.qmd
  - Docker: docker.qmd
  - About: about.qmd
  - Jenkins: jenkins.qmd
  - About: about.qmd
  - Amazon: amazon.qmd
  - About: about.qmd
  - Github: indexgit.qmd
  - About: about.qmd
  - Contact: contact.qmd
  - About: about.qmd
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    mermaid: {}
 
